'use client'

export default function ArtifactsPage() {
  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold text-white mb-6">Artifact Explorer</h1>
      <div className="bg-slate-800/50 rounded-lg border border-slate-700 p-8 text-center">
        <p className="text-slate-400 mb-4">Walrus artifact browser coming in Phase 3</p>
        <p className="text-slate-500 text-sm">Browse and preview all artifacts generated by agents with CID-based file retrieval</p>
      </div>
    </div>
  )
}
